In [ ]:
import numpy as np

***empty*** creates an array whose initial content is random and depends on the state of the memory.

In [ ]:
np.empty(2)

array([4.6704843e-310, 0.0000000e+000])

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the ***dtype*** keyword.

In [ ]:
arr = np.ones(2, dtype=np.int64)
arr

array([1, 1])

In [ ]:
arr_3d = np.array([[[0, 1, 2, 3],
                    [4, 5, 6, 7]],

                   [[0, 1, 2, 3],
                    [4, 5, 6, 7]],

                   [[0, 1, 2, 3],
                    [4, 5, 6, 7]]])


***ndim*** will tell you the number of axes, or dimensions, of the array.

In [ ]:
arr_3d.ndim

3

***size*** will tell you the total number of elements of the array.

In [ ]:
arr_3d.size

24

***shape*** will display a tuple of integers that indicate the number of elements stored along each dimension of the array.



In [ ]:
arr_3d.shape

(3, 2, 4)

***arange*** is used to create an array with a range of elements. The parameters are first number, last number and the step size respectively.

In [ ]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [ ]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


***reshape*** will give a new shape to an array without changing the data.

In [ ]:
new_arr = arr.reshape(3,2)
print(new_arr)

[[0 1]
 [2 3]
 [4 5]]


***resize*** will resize an array in-place.

In [ ]:
arr = np.array([[0,1],[2,3]])

In [ ]:
np.resize(arr,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

***flatten*** is used to convert your array into a 1D array.

In [ ]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])